### ISSUE TITLE
개발 환경 설치 과정

### ISSUE THREAD

**Issue by ljh1324** [ljh1324/react_storybook_cicd#1]
# 개발 환경 설치 과정

1. cra를 통한 react-app 타입스크립트 버전 생성
```shell
$ npx create-react-app my-app --typescript
```
2. node-sass, classnames 라이브러리 설치
```shell
$ npm install --save node-sass
$ npm install --save @types/classnames
```

3. storybook 설치
```shell
$ npx -p @storybook/cli sb init
```

4. 동작 확인
```jsx
import React from 'react';
import className from 'classnames/bind';

import style from './App.module.scss';  // scss 파일명은 반드시 *.module.scss

const cx = className.bind(style);

function App() {
    return (
        <div className={cx('App')}>
            Hello CRA!
        </div>
    );
}

export default App;
```

```scss
.App {
    font-size: 25px;
    font-weight: bold;
    text-align: center;
    color: #1ea7fd;
    background-color: #000;
}
```
**결과 화면**
![image](https://user-images.githubusercontent.com/20397041/91631530-2d184700-ea15-11ea-8651-1c4db1d9d69b.png)
